sudo: false

language: ruby

rvm:
  - 2.6.5

cache: bundler

services:
  - xvfb

addons:
  firefox: 70.0

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
